### ISSUE TITLE
[Query] Match fields case insensitive

### ISSUE THREAD

**Issue by Studio384** [optimise-group/bifrost#78]
**Describe the bug**
When searching in the contacts list, search will correctly filter out all fields regardless of cases except for company. When searching based on a company name, the query becomes case sensitive for that field.

**To Reproduce**
1. Have a contact with a company name set.
2. Search for the company name but alter the casing from the provided data. (e.g. search for `sippy` when `Sippy` is set as company name)
3. Bifrost will filter out the contact despite the expected match.

**Expected behavior**
The contacts with the company name "Sippy" should appear when searching for "sippy".

**Logs**

**Environment (please complete the following information):**
- OS: Windows 11
- Erlang/Elixir version: Erlang 24, Elixier 1.12
- Version/Commit: 257810a5

**Additional context**
NA

**Comment by timothyvanderaerden** [comment]
This is actually happening on all match queries (and all fields).
