### ISSUE TITLE
[Contacts] Sorting behavior suggestions

### ISSUE THREAD

**Issue by Studio384** [optimise-group/bifrost#87]
**Is your feature request related to a problem? Please describe.**
To the front-end and the user, whenever showing all contacts in a list, it makes little sense to distinguish between first, middle, and last name over the full name. As a result, with the exception to the contact settings, these names are always shown together as a seemingly continuous string. This makes for unexpected behavior when using sorting. For example:

| firstname | lastname |
| --- | --- |
| Emmely | Reumans |
| Emmely | Bosmans |
| Emmely | van Maaren |

These names will always be shown to the user as "Emmely Bosmans" and "Emmely van Maaren", most relevant in the UI in the contacts list where the name is a single column. This column will always sort on first name because the first name is also shown first in the UI and this gives the most logical behavior.

The 3 given examples however will always show in order of creation (or in reverse order depending or ascending or descending sorting).

A similar behavior happens for contacts without a (first) name, and especially contacts that are only a company. These will all be thrown together at the bottom (for ascending) or top (for descending) of the list in a seemingly random order.

**Describe the solution you'd like**
The `firstName`/`middleName`/`lastName` and `company` filters should behave less explicit in their sorting methods.

For the name, the most logical solution is for the `firstName` sort to also sort on `middleName` and `lastName`, similar to how other contact apps like Outlook and Google Contacts behave. 

To solve the problem when it is a company contact, it should also put the `company` field as an equal and include that in the sorting when sorting by name or (and probably easier to do) at least sort the companies at the end of the list by company as well.

Not described as a problem above, but a logical extention to this issue: when sorting by `company`, also sort by the contact name. Right now sorting by company will result in a seemingly random list of contacts within that company, it would be better if it then would continue to sort by name.

**Describe alternatives you've considered**
Splitting up the first, middle, and last name into their own columns in the contacts list. This would provide a logical place to add sorting options for middle and last names but brings other issues:

* This goes against what all contact apps do, and thus probably also against user expectations.
* Given how Sippy 2 is currently being used, this would make for a lot of empty fields in the list.
* For empty fields, it would still result in the seemingly random sorting when the fields are left empty for contacts.

**Comment by timothyvanderaerden** [comment]
@Studio384 can you test #88 and report your findings?
